### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 1, column 54

### ISSUE THREAD

**Issue by pergolafabio** [pkkid/python-plexapi#440]
Hi,

i installed this plugin on my PMS server: https://github.com/d8ahazard/Cast.bundle
when i play something with code below, it actualy plays, but i always receice this error below

what could be the cause?

```
film = plex.library.section('Movies').get('Terminator Genisys')
client = plex.client("TV Samsung")
client.playMedia(film)

```
```
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 11, in <module>
    client.playMedia(film)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 486, in playMedia
    }, **params))
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 204, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 168, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54
```

**Comment by jjlawren** [comment]
I was actually trying to track down this error from a Samsung TV. Would you be able to run this script while media is playing and provide the output? Make sure not to share your token.

```
from plexapi.client import PlexClient
import logging

log = logging.getLogger()
log.addHandler(logging.StreamHandler())
log.setLevel(logging.DEBUG)

clienturl = 'http://<SAMSUNG_TV_IP>:32400'
token = '<YOUR_TOKEN_HERE>'

samsung = PlexClient(baseurl=clienturl, token=token)
print(samsung.pause())

```

**Comment by pergolafabio** [comment]
Ok, Will try asap, but my samsung tv is reported as 127.0.0.1, should I use that ip ? Or Plex server IP or the actual real up from Samsung? Then I need to look it up in network settings...

I also use home assistant, I setup the Plex integration there, it also reports the same error...
```

<MediaContainer size="1">
<Server name="TV Samsung" host="127.0.0.1" address="127.0.0.1" port="32400" machineIdentifier="mtcjs3w774g7i" version="2.012" protocol="plex" product="Plex for Samsung" deviceClass="tv" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
```
</MediaContainer>

**Comment by jjlawren** [comment]
Try this instead:
```
from plexapi.server import PlexServer
import logging

log = logging.getLogger()
log.addHandler(logging.StreamHandler())
log.setLevel(logging.DEBUG)

serverurl = 'http://<SERVER_IP>:32400'
token = '<YOUR_TOKEN_HERE>'

server = PlexServer(baseurl=serverurl, token=token)
samsung = server.client("TV Samsung")
samsung.proxyThroughServer()
print(samsung.pause())
```
Luckily the error is cosmetic and doesn't affect functionality, but it would still be nice to fix.

**Comment by pergolafabio** [comment]
It's indeed cosmetic... That script seems better to test, will do asap...

Do you think my other issue is also related?
https://github.com/pkkid/python-plexapi/issues/439

Thats not a cosmetic one ;) sometimes I can play, sometimes not... No idea to replicate...
If I try 5 times to play, 1 is successful

**Comment by pergolafabio** [comment]
here is output:

```
Starting new HTTP connection (1): 192.168.0.14:32400
http://192.168.0.14:32400 "GET / HTTP/1.1" 200 2107
http://192.168.0.14:32400 "GET /clients HTTP/1.1" 200 331
http://192.168.0.14:32400 "GET /player/playback/pause?commandID=1&type=video HTTP/1.1" 200 None
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 27, in <module>
    print(samsung.pause())
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 319, in pause
    self.sendCommand('playback/pause', type=mtype)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 204, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\server.py", line 383, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54

Process finished with exit code 1
```

**Comment by jjlawren** [comment]
Still not seeing the raw response. Let's go simpler:
```curl 'http://192.168.0.14:32400/player/playback/pause?X-Plex-Token=<TOKEN>&commandID=1'```
The other issue seems unrelated to this one.

**Comment by pergolafabio** [comment]
gives me this : 

➜  ~ curl 'http://192.168.0.14:32400/player/playback/pause?X-Plex-Token=xxx&commandID=1'
<html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>#

**Comment by jjlawren** [comment]
Yeah, that's what I was seeing elsewhere. The player actually pauses, though, correct?

**Comment by pergolafabio** [comment]
no, with that curl command, it doesnt pause
with that script earlier, it did pause / resume

**Comment by jjlawren** [comment]
Try with adding `&type=video` to the end.

**Comment by pergolafabio** [comment]
same 400 bad request error :-)

**Comment by blacktwin** [comment]
> xml.etree.ElementTree.ParseError: no element found: line 1, column 54

This error may actually be fine, especially if the command is actually going through. This error message will likely be resolved with this [fix](https://github.com/pkkid/python-plexapi/pull/437/commits/06ca74dbcea38372ddcf4b0e7e4139ff124c9adb#diff-a7fdc8e68f5c536ce8e881262243424dR566-R569). You can try it yourself or wait for the fix to be pushed when that PR is merged.

The error could be that the returned response is not an xml. Try debugging the response from the command that causes that error.

**Comment by pergolafabio** [comment]
ok, to test that fix, do i just need to replace this file : 

https://github.com/pkkid/python-plexapi/blob/06ca74dbcea38372ddcf4b0e7e4139ff124c9adb/plexapi/media.py

or more?

cause if replace that file, i get connection errors
even a simple code like below doesnt fire

```
movies = plex.library.section('Kids')
for video in movies.search(unwatched=True):
    print(video.title)
```

**Comment by pergolafabio** [comment]
also, on pypi site, i see a new version 3.3.0 ; on github i see in release section only 3.2.0 as latest
how is that possible?

**Comment by pergolafabio** [comment]
ok, nevermind, i tried again with that new media.py file, now it works

but still have the same xml error 

```
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 13, in <module>
    client.playMedia(film)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 496, in playMedia
    }, **params))
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 204, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\server.py", line 383, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54
```

**Comment by blacktwin** [comment]
Sorry, I kinda mislead you. It not the media.py file but the code in the file that is calling the query. The client.py has a similar query call that is failing due to a non xml return. Again if the commands work then you can ignore the error message.

**Comment by blacktwin** [comment]
Sorry, I kinda mislead you. It not the media.py file but the code in the file that is calling the query. The client.py has a similar query call that is failing due to a non xml return. Again if the commands work then you can ignore the error message.

**Comment by pergolafabio** [comment]
yeah, it works, but it would be nice that i dont have that error :)
my home assistant log is now flooded wih those :)

kids using this now a lot, using it as a google voice assistant :-)

**Comment by pergolafabio** [comment]
But is there a fix coming or not? Do I also need to replace the client.py file to test ?

**Comment by jjlawren** [comment]
@blacktwin there's already a check for this error for specific clients in the `sendCommand()` client call:
https://github.com/pkkid/python-plexapi/blob/c0f2c056270b4456307333a9a3efcc8611034912/plexapi/client.py#L203-L213

Most of those clients return something like `b'OK'` which is not valid XML. The Samsung player returns some other value (which may just be the 'Bad Request' HTML response) but it's probably best to confirm what that data is first.

**Comment by pergolafabio** [comment]
Ok , can I test that and include "TV Samsung" in that list array? Does it need to be the client name?

**Comment by jjlawren** [comment]
Since it's checking against the product it would be "Plex for Samsung". That should keep the error from happening. I'd still like to understand what bad response it's giving us, though.

**Comment by pergolafabio** [comment]
How can I provide you that info?

**Comment by jjlawren** [comment]
If you're comfortable messing with the library, edit it to print out the data before it throws the exception:
```diff --git a/plexapi/client.py b/plexapi/client.py
index 36cf8d0..807429d 100644
--- a/plexapi/client.py
+++ b/plexapi/client.py
@@ -165,6 +165,7 @@ class PlexClient(PlexObject):
             log.warning('BadRequest (%s) %s %s; %s' % (response.status_code, codename, response.url, errtext))
             raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
         data = response.text.encode('utf8')
+        print(data)
         return ElementTree.fromstring(data) if data.strip() else None
```
And then run the script from [this comment](https://github.com/pkkid/python-plexapi/issues/440#issuecomment-605391664) again.

**Comment by pergolafabio** [comment]
as requested : 

```
Starting new HTTP connection (1): 192.168.0.14:32400
http://192.168.0.14:32400 "GET / HTTP/1.1" 200 2106
http://192.168.0.14:32400 "GET /clients HTTP/1.1" 200 340
http://192.168.0.14:32400 "GET /player/playback/pause?commandID=1&type=video HTTP/1.1" 200 None
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 30, in <module>
    print(samsung.pause())
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 320, in pause
    self.sendCommand('playback/pause', type=mtype)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 205, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\server.py", line 383, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54
```

**Comment by pergolafabio** [comment]
and this helps indeed :-)

```
            if self.product in (
                'Plexamp',
                'Plex for Android (TV)',
                'Plex for Samsung',
```

**Comment by jjlawren** [comment]
Did you edit `D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py`?

If so, try changing the `print(` to `log.error(` instead. Seems like stdout isn't going anywhere.

**Comment by pergolafabio** [comment]
yes, i am changing that file, its just local on my notebook to test stuff
now its like : 

```
        data = response.text.encode('utf8')
        log.error(data)
```

so i play media, then run that log script

but still produces now error below, looks the same
everyime i run script, the movie pauses/resumes

```
http://192.168.0.14:32400 "GET / HTTP/1.1" 200 2106
http://192.168.0.14:32400 "GET /clients HTTP/1.1" 200 340
http://192.168.0.14:32400 "GET /player/playback/pause?commandID=1&type=video HTTP/1.1" 200 None
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 30, in <module>
    print(samsung.pause())
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 321, in pause
    self.sendCommand('playback/pause', type=mtype)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 205, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\server.py", line 383, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54
```

**Comment by jjlawren** [comment]
Oops, it's happening at the end of the `query()` method in `server.py`. Can you add the log call there?

**Comment by pergolafabio** [comment]
thats produces indeed some more info :-)

```
Starting new HTTP connection (1): 192.168.0.14:32400
http://192.168.0.14:32400 "GET / HTTP/1.1" 200 2106
b'<?xml version="1.0" encoding="UTF-8"?>\n<MediaContainer size="24" allowCameraUpload="1" allowChannelAccess="1" allowMediaDeletion="1" allowSharing="1" allowSync="0" allowTuners="0" backgroundProcessing="1" companionProxy="1" countryCode="bel" diagnostics="logs,databases,streaminglogs" eventStream="1" friendlyName="Synology" hubSearch="1" itemClusters="1" livetv="7" machineIdentifier="d0a25cbfa6fcc44d766dfea3abfc23b54c4caa5d" mediaProviders="1" multiuser="1" myPlex="1" myPlexMappingState="mapped" myPlexSigninState="ok" myPlexSubscription="0" myPlexUsername="pergola.fabio@gmail.com" ownerFeatures="04d7d794-b76c-49ef-9184-52f8f1f501ee,07f804e6-28e6-4beb-b5c3-f2aefc88b938,0eee866d-782b-4dfd-b42b-3bbe8eb0af16,1417df52-986e-4e4b-8dcd-3997fbc5c976,16d69c53-4c40-4821-b9f3-57ca690b2d4d,228a6439-ee2f-4a9b-b0fc-1bfcd48b5095,24b4cf36-b296-4002-86b7-f1adb657e76a,2797e341-b062-46ed-862f-0acbba5dd522,2ea0e464-ea4f-4be2-97c1-ce6ed4b377dd,300231e0-69aa-4dce-97f4-52d8c00e3e8c,34e182bd-2f62-4678-a9e9-d13b3e25019d,5b6190a9-77a4-477e-9fbc-c8118e35a4c1,5d819d02-5d04-4116-8eec-f49def4e2d6f,5e2a89ec-fb26-4234-b66e-14d37f35dff2,644c4466-05fa-45e0-a478-c594cf81778f,65685ff8-4375-4e4c-a806-ec1f0b4a8b7f,78643fe5-d192-40c7-8e93-5ccf04c0b767,7e7596aa-6e2c-41d1-a460-1e13cf0b62f2,85ebfb7b-77fb-4afd-bb1a-2fe2fefdddbe,86da2200-58db-4d78-ba46-f146ba25906b,8e8dd5c8-14a4-4208-97d4-623e09191774,96cac76e-c5bc-4596-87eb-4fdfef9aaa11,98872b06-2ff3-4b71-96bc-039e2ebe7adc,a19d495a-1cef-4f7c-ab77-5186e63e17f7,a3d2d5c4-46a0-436e-a2d6-80d26f32b369,a536a6e1-0ece-498a-bf64-99b53c27de3a,abd37b14-706c-461f-8255-fa9563882af3,adaptive_bitrate,b20d91ca-1b2f-45a2-a115-c1ad24c66ac5,b2403ac6-4885-4971-8b96-59353fd87c72,b46d16ae-cbd6-4226-8ee9-ab2b27e5dd42,b5874ecb-6610-47b2-8906-1b5a897acb02,bfeaee4e-965a-4d24-b163-020c3c57d936,c55d5900-b546-416d-a8c5-45b24a13e9bc,c7ae6f8f-05e6-48bb-9024-c05c1dc3c43e,camera_upload,collections,d14556be-ae6d-4407-89d0-b83953f4789a,d2013aee-359d-4a02-b1f0-b8b692881be1,d20f9af2-fdb1-4927-99eb-a2eb8fbff799,d9f42aea-bc9d-47db-9814-cd7a577aff48,dab501df-5d99-48ef-afc2-3e839e4ddc9a,download_certificates,e7cea823-02e5-48c4-a501-d37b82bf132f,ee352392-2934-4061-ba35-5f3189f19ab4,f8ea4f37-c554-476a-8852-1cbd2912f3f6,fb34e64d-cd89-47b8-8bae-a6d20c542bae,fec722a0-a6d4-4fbd-96dc-4ffb02b072c5,federated-auth,home,kevin-bacon,livetv,loudness,radio,server-manager,shared-radio,type-first,unsupportedtuners" photoAutoTag="1" platform="Linux" platformVersion="DSM 6.1.7.15284-3" pluginHost="1" pushNotifications="0" readOnlyLibraries="0" requestParametersInCookie="1" streamingBrainABRVersion="3" streamingBrainVersion="2" sync="1" transcoderActiveVideoSessions="0" transcoderAudio="1" transcoderLyrics="1" transcoderPhoto="1" transcoderSubtitles="1" transcoderVideo="1" transcoderVideoBitrates="64,96,208,320,720,1500,2000,3000,4000,8000,10000,12000,20000" transcoderVideoQualities="0,1,2,3,4,5,6,7,8,9,10,11,12" transcoderVideoResolutions="128,128,160,240,320,480,768,720,720,1080,1080,1080,1080" updatedAt="1585500884" updater="1" version="1.18.8.2527-740d4c206" voiceSearch="1">\n<Directory count="1" key="activities" title="activities" />\n<Directory count="1" key="butler" title="butler" />\n<Directory count="1" key="channels" title="channels" />\n<Directory count="1" key="clients" title="clients" />\n<Directory count="1" key="devices" title="devices" />\n<Directory count="1" key="diagnostics" title="diagnostics" />\n<Directory count="1" key="hubs" title="hubs" />\n<Directory count="2" key="library" title="library" />\n<Directory count="3" key="livetv" title="livetv" />\n<Directory count="3" key="media" title="media" />\n<Directory count="1" key="metadata" title="metadata" />\n<Directory count="1" key="neighborhood" title="neighborhood" />\n<Directory count="1" key="playQueues" title="playQueues" />\n<Directory count="1" key="player" title="player" />\n<Directory count="1" key="playlists" title="playlists" />\n<Directory count="1" key="resources" title="resources" />\n<Directory count="1" key="search" title="search" />\n<Directory count="1" key="server" title="server" />\n<Directory count="1" key="servers" title="servers" />\n<Directory count="1" key="statistics" title="statistics" />\n<Directory count="1" key="system" title="system" />\n<Directory count="1" key="transcode" title="transcode" />\n<Directory count="1" key="updater" title="updater" />\n<Directory count="1" key="user" title="user" />\n</MediaContainer>\n'
http://192.168.0.14:32400 "GET /clients HTTP/1.1" 200 340
b'<?xml version="1.0" encoding="UTF-8"?>\n<MediaContainer size="3">\n<Server name="TV UE32H5500" host="127.0.0.1" address="127.0.0.1" port="32400" machineIdentifier="u7cj6otem5ty6" version="2.012" protocol="plex" product="Plex for Samsung" deviceClass="tv" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" />\n<Server name="TV UE32H5500" host="192.168.0.14" address="192.168.0.14" port="32400" machineIdentifier="u7cj6otem5ty6" version="2.012" protocol="plex" product="Plex for Samsung" deviceClass="tv" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" />\n<Server name="Chrome" host="192.168.0.14" address="192.168.0.14" port="32400" machineIdentifier="n1uk0syazlonhbwkhzc110cd" version="4.30.1" protocol="plex" product="Plex Web" deviceClass="pc" protocolVersion="3" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" />\n</MediaContainer>\n'
http://192.168.0.14:32400 "GET /player/playback/pause?commandID=1&type=video HTTP/1.1" 200 None
b'<?xml version="1.0"?><Response code="200" status="OK">'
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 30, in <module>
    print(samsung.pause())
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 321, in pause
    self.sendCommand('playback/pause', type=mtype)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 205, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\server.py", line 384, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54
```

**Comment by jjlawren** [comment]
Ok, so just a bad response:
```
b'<?xml version="1.0"?><Response code="200" status="OK">'
```
I'll make a PR to skip this client as I have another example to add.

**Comment by pergolafabio** [comment]
like those 2 ?

                'Plexamp',
                'Plex for Android (TV)',
